//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedData
    {
        public int id { get; set; }
        public int stockID { get; set; }
        public System.DateTime timestamp { get; set; }
        public double price { get; set; }
        public double volume { get; set; }
    
        public virtual StockIndex StockIndex { get; set; }
    }
}
