//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQuoteLog
    {
        public int ID { get; set; }
        public int stockIndexID { get; set; }
        public System.DateTime timeStamp { get; set; }
        public float lastSale { get; set; }
        public float volume { get; set; }
        public float askSize { get; set; }
        public float bidSize { get; set; }
    }
}
