//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdClassLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stdataEntities : DbContext
    {
        public stdataEntities()
            : base("name=stdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StockIndex> StockIndexes { get; set; }
        public virtual DbSet<StockQuoteLog> StockQuoteLogs { get; set; }
        public virtual DbSet<LoggedData> LoggedDatas { get; set; }
        public virtual DbSet<LoggedTimeRanx> LoggedTimeRanges { get; set; }
    }
}
