//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockDataMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIndex
    {
        public int ID { get; set; }
        public string tickerName { get; set; }
        public string companyName { get; set; }
        public string notes { get; set; }
    }
}
